version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
  # Maintain dependencies for Pip
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "daily"
