AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'A serverless authentication solution which converts Auth0 JWT tokens to AWS Cloudfront signed cookies'

Globals:
  Api:
    EndpointConfiguration: 'EDGE'
    Cors: "'*'"

Resources:
  ConvertJWTFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'convert-jwt'
      Description: 'Convert an Auth0 JWT token to an AWS Cloudfront signed cookie'
      CodeUri: 'src/'
      Handler: 'app.lambdaHandler'
      Runtime: 'nodejs8.10'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action: 'ssm:DescribeParameters'
              Resource: '*'
            - Effect: 'Allow'
              Action: 'ssm:GetParameter'
              Resource: 'arn:aws:ssm:*:*:parameter/cloudfront-private-key'
      Environment:
        Variables:
          KEY_PAIR_ID: 'APKAII5737THEDVGPERA'
          PRIVATE_KEY_PARAM_NAME: 'cloudfront-private-key'
          AUTH0_PUB_KEY: |-
            -----BEGIN CERTIFICATE-----
            MIIDATCCAemgAwIBAgIJWU08l7SJIJXEMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
            BAMTE21lbHZ5bi5ldS5hdXRoMC5jb20wHhcNMTkwNjA0MTgzNzEwWhcNMzMwMjEw
            MTgzNzEwWjAeMRwwGgYDVQQDExNtZWx2eW4uZXUuYXV0aDAuY29tMIIBIjANBgkq
            hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0EFVSAksg77kE4wPz+ezXVnRSFk7v4jC
            uTdpy3bI0lcuZt7bDfgahKHLAhuas0IRQ8Q8rLt2R+cSPGAd2DlfR3K2ILhWxukm
            AR4GHeCohjqx9oTwLMCxHEeCge+NCTEvg47+lqnKR7/zGcXz/aFM731QobgtGvuJ
            ywvVuGmvrzDrrcBgQXvEoPX7fNT+Vd3/I+ZMa+POj/YgtfMP+l81bwJuIYyYIs/U
            Fn7Djg2PJ3IrUZ+1usdGV6eKD55P+nzf5ndl2qD2mSi+wgFwSN3yel2xIdSsurrs
            eqZDZbx56EMQpANqexPyPOWIdd3b9Vjc0ujwE3X5dCXjAVJz6FHMdwIDAQABo0Iw
            QDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRLL4c7ImFPg51N2MiN1FmlhVlM
            ljAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAMgAdrK5Y2XsVDzf
            ICA3XJgydSzzxbdpvQobC6t2MBLjpWCUFnyS3NPGTp+35LpO+jbnMl0NWiopyL0G
            Bixj7yG9fKuWDBBNFZ2x7eDCZYBp5Dr97N08BOH8nJYDp6OZlq6rAvpjRnq21eyv
            AItjmIWX28wiaMTqVl9j9xfsVhPMPcuFax4MZvZJfwUSb8qnFNrbeBmLatWI8eAb
            hBeaMEXdA2xih/76GNw68W5dnBAeLT5nPpTFWIe+9p6vHVEdwVpLSU0/D/JPWd0g
            fhZGWC3YafLnmVqgAr1Izsz1yiDRPegxjeiS1lcgdKYtBKlNZkfSOtqp/mJwy4vS
            LYtI4A4=
            -----END CERTIFICATE-----
      Events:
        ConvertJWTApi:
          Type: 'Api'
          Properties:
            Path: '/convert-jwt'
            Method: 'get'
