name: "Codecov"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/codecov.yml'
      - 'src/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate coverage report
        working-directory: src
        run: |
          pip install poetry
          poetry install
          poetry build
          poetry run pytest --cov=./ --cov-report=xml
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: python-coverage
          path: src/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: src/coverage.xml
          flags: unittests
          verbose: true
